### ISSUE TITLE
Feature request: additional information from valuesets()

### ISSUE THREAD

**Issue by TimTaylor** [fragla/eq5d#11]
It would be a nice addition to the `valuesets()` function if it could also return some additional information such as the year (and possibly DOI) of the associated paper.

**Comment by fragla** [comment]
Yes, agree. This is something I've thought about doing previously (and incorporating into the shiny app). I've got most of the info in the data.R file, I just need to get a few DOIs for some of the book chapters I used and to double check the value set years. Will add before the next release.

**Comment by TimTaylor** [comment]
@fragla would you be ok if I started working on a minimal PR for this (probably just a column of DOIs). I'm currently working on a package to assist colleagues in modelling qaly losses (https://github.com/TimTaylor/qalytools) and will need to ensure they have correct citations for value sets.

**Comment by fragla** [comment]
@TimTaylor sure, no problem. Sorry I've not managed to get round to doing this. I've attached a file with DOIs/PubMed IDs/other links that I was part way through pulling together - hopefully this will help. Rather than referencing the EQ-5D books for 3L TTO/VAS value sets as I'd done for type documentation (e.g. in `?TTO`) I was going to use the individual manuscript references, but there's still a few to get.

[valuesets.csv](https://github.com/fragla/eq5d/files/9179723/valuesets.csv)

**Comment by TimTaylor** [comment]
Cool. I'll start a draft PR and add to it incrementally. Can then squash / merge as appropriate when finished.

**Comment by fragla** [comment]
Implemented by #24.
