### ISSUE TITLE
error running EQ5D package 

### ISSUE THREAD

**Issue by amaniahmed33** [fragla/eq5d#7]
Hi there, 

Every time I run the EQ5D3L function it gives me an error on type = "TTO" & = "VAS" as well.

I tried to make R read the VAS and the TTO from my own database and it gave me an error as well.
What to do, please 

Thanks in advance

**Comment by fragla** [comment]
Hi

Can you share an example of the code you are trying to run and the error message? Also, what is the object type the dimension scores stored in (e.g. data.frame, character vector etc).

Normally I would recommend using the eq5d function rather than calling the eq5d3l function directly as this handles the different object types that the data may be in.

e.g. eq5d(scores=scores, country="UK", version="3L", type="TTO")

Here the scores variable can be a data.frame (with columns MO, SC, UA, PD and AD), a named vector (e.g. c(MO=1,SC=2,UA=3,PD=2,AD=1)) or scores in five digit format.


________________________________

**Comment by fragla** [comment]
No further response from user so closing issue.
